version: ~> 1.0

env:
  global:
    - secure: "YOHsIeL9YaHqJtgxGXG0ZP13s9ZCx3Q0oRlaIjEYM4vgcKoWmgmGn0SZaXXGeMMus5XJDm7HxS7/MmT1ddv7n+vzUGVxPh3moC2tIv5N4KbwuG+lgrw97qIPeKtd2CE0D+J3qpKnZh9DnBvGYmfNLalb9JHwVei16qPOUE802YSXogoLXESjI/dFkcSTGiPeCIjuRSpdVytDFx7H3JDukqgjuOUYoqyErsfIAxC0QMA8Fr6Cn8GMvuo9tbx8pB/xePM9VXl1gnhz8eHS9bF+zicnCK18X9OELAKpEmrU2r2MJU4pExOem8OAo3XVNi8mSWInWMeMiwJDGm/2/i4WKqUci0ri2tOEOzU020eiSY6430w3+KcRcB1G3VRB5TgEQaTnwk8Gi5+wWm33BlN6XhSzm0ZLswhyLS/1AVc1VCbVcQCv/U9Exe6WblLfLYzM7dgObqzLkJtbkUcZfucRsIkXS0rg0V1Qd4YTGjO7PV4sg4grQix1aQYgYSbMB+sAqNObka3GLBb2E6VAk5/1h2U1bdUM7H5IEuYwKm9am9jz7gcbXEhLSb2RzVF4hJrGT2xbwWSyO/S/wf7X9GtbOZe9pMgwOGvZ+HSxenXMpT/8bH9zyE0yYi30XCjvndlAk8SVfgFArEVQuD6R6u3PeuPagBMH/FVyKRaOenuc6Os="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="psdm_qs_cli"

    # The name of the conda package
    - CONDA_PACKAGE="psdm_qs_cli"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    # pandoc/pypandoc - used to translate README.md for sphinx
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS="."

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
